name: schools_management
description: A new Flutter project.

version: 6.1.0+19

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  smooth_page_indicator: ^1.0.0+2
  simple_animations: ^2.5.1
  provider: any
  google_fonts: ^1.1.0
  carousel_slider: ^4.0.0
  geolocator: ^6.0.0
  background_location: ^0.1.2
  geocoder: ^0.2.1
  date_utils: ^0.1.0+3
  flutter_calendar_carousel: ^1.5.3
  countup: ^0.1.3
  local_auth: ^0.6.3+2
  rflutter_alert: ^1.0.2
  syncfusion_flutter_charts: ^18.4.49
  camera: ^0.5.8+7
  image_picker: 0.6.7+22
  pull_to_refresh: ^2.0.0
  shared_preferences: ^0.5.12
  connectivity: ^2.0.2
  percent_indicator: ^2.1.9+1
  table_calendar: ^2.2.2
  sqflite: ^1.1.7+2
  trust_location: ^2.0.11
  location_permissions: ^3.0.0
  shimmer: ^1.1.2
  cached_network_image: ^2.5.0
  flutter_svg: ^0.19.3
  blinking_text: ^1.0.1+2
  fluentui_system_icons: ^1.1.101
  auto_size_text: ^2.1.0
  awesome_dialog: ^1.3.2
  sizer: ^1.1.0
  permission_handler: ^5.1.0+2
  lottie: ^0.7.0+1
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.3.2
  flutter_launcher_icons: ^0.8.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/intek_besar.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo3.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/healthcare1.png
    - assets/images/SII.png
    - assets/images/logo-intek.png
    - assets/images/intek_besar.png
    - assets/images/full.png
    - assets/images/intek.png
    - dev_assets/
    #  - dev_assets/ss.png
    #  - dev_assets/login_bg.png
    - dev_assets/home_bg.png
    - dev_assets/paytm/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
